name: My First Action

on: push  # Runs when code is pushed

jobs:
  my-job: #Here you put the name of the job
    runs-on: ubuntu-latest # The CI-CD pipeline will run on Ubuntu
    steps:
      - name: Checkout code
        run: git clone https://github.com/HadasZeldin/yalla  # Gets the latest code, in other words it does 'git clone'
      - name: the ls-la command
        run: 'ls-la'
      - name: Print Hello World
        run: echo "Hello, GitHub Actions!" # This is just the command
